# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, FTR-actions, FTR-sabotage, FTR-fix ]
  pull_request:
    branches: [ main, FTR-actions, FTR-sabotage, FTR-fix ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  compile:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Compile The Code
        run: |
          javac -cp "src/" src/*.java

         
  TestMapMove:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: compile and run map move tests
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/TestMapMove.java tests/TestMapMove.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapMove

  TestGhostMove:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: compile and run ghost move tests
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/TestMapMove.java tests/TestGhostMove.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostMove

  TestPacmanMove:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: compile and run pacman move tests
        run: |
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/TestMapMove.java tests/TestPacmanMove.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacmanMove

  testGhostValidMoves:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      container: openjdk

      steps:
      # Runs a set of commands using the runners shell
      - name: Test GhostValidMoves
        run:
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/TestMapMove.java tests/TestGhostValidMoves.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestGhostValidMoves

  testMapGetLoc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk

    steps:
      # Runs a set of commands using the runners shell
      - name: Test MapGetLoc
        run:
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/TestMapMove.java tests/TestMapGetLoc.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestMapGetLoc

  testPacManValidMoves:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: openjdk
    
    steps:
      # Runs a set of commands using the runners shell
      - name: Test PacManValidMoves
        run:
          javac -cp "tests/junit-4.10.jar:src/:tests/" src/TestMapMove.java tests/TestPacManValidMoves.java
          java -cp "tests/junit-4.10.jar:src/:tests/" org.junit.runner.JUnitCore TestPacManValidMoves

